apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-deploy
  labels:
    app: bigbluebutton

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigbluebutton
  template:
    metadata:
      labels:
        app: bigbluebutton
    spec:
      containers:
        - name: bbb
          image: bigbluebutton/bigbluebutton
          #env:
          # - name:
          #    value:
          ports:
            - name: seksen
              containerPort: 80
            - name: otuzbes
              containerPort: 1935
            - name: yetmissekiz
              containerPort: 3478


---
apiVersion: v1
kind: Service
metadata:
  name: bbb-service
spec:
  selector:
    app: bigbluebutton
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: UDP
      port: 3478
      targetPort: 3478
    - protocol: TCP
      port: 1935 
      targetPort: 1935
